VIEW_NEWS_WEIGHT = 0.5
COLLECTION_NEWS_WEIGHT = 1.0
DEL_COLLECTION_NEWS_WEIGHT = -1.0
COMMIT_WEIGHT = 0.4
FOCUS_WEIGHT = 0.3
DEL_FOCUS_WEIGHT = -0.3
RELEASE_NEWS_WEIGHT = 1.2
USER_BEHAVIOR_WEIGHT = {'VIEW_NEWS': VIEW_NEWS_WEIGHT,
                        'COLLECTION': COLLECTION_NEWS_WEIGHT,
                        'DEL_COLLECTION': DEL_COLLECTION_NEWS_WEIGHT,
                        'COMMIT': COMMIT_WEIGHT,
                        'FOCUS': FOCUS_WEIGHT,
                        'DEL_FOCUS': DEL_FOCUS_WEIGHT,
                        'RELEASE_NEWS': RELEASE_NEWS_WEIGHT}

INIT_CATEGORY_WEIGHT = 0.1

CRISIS_VALUE = 0.1
RANDOM_CRISIS_VALUE = 0.1

USER_LABEL_HALF_TIME = 300

WEIGHT_CONTROL = 0.5

USER_NEWS_TIME_VALUE = 3600 * 7
